import { KeyValue } from "../interfaces/general";

export const shortKeys = {
  i: "isEncoded",
  x: "api_key",
  a: "action",
  e: "event",
  d: "description",
  s: "session_id",
  v: "version",
  c: "cacheKey",
  b: "baseUrl",
  l: "adBlock",
  o: "cookies",
  n: "do_not_track",
  q: "absoluteResolution",
  w: "availableResolution",
  p: "nativeResolution",
  f: "battery_charging",
  h: "battery_chargingTime",
  j: "battery_dischargingTime",
  k: "battery_level",
  m: "city",
  z: "country_code",
  g: "language",
  t: "time_zone",
  r: "referrer",
  y: "title",
  u: "url",
  aa: "continent",
  ab: "accuracy_radius",
  ac: "latitude",
  ad: "longitude",
  ae: "region_code",
  af: "region_name"
} as KeyValue;
